install:
	pip3 install scikit-learn

test-knn:
	python3 lab5_test.py test-knn

test-dt:
	python3 lab5_test.py test-dt

test-svm:
	python3 lab5_test.py test-svm

test-nn:
	python3 lab5_test.py test-nn
